apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nightbot-squads
  namespace: <%= $.namespace %>
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: nightbot-squads
        app: nightbot-squads
    spec:
      containers:
      - image: mrgalaxy/nightbot-squads:latest
        name: nightbot-squads
        imagePullPolicy: Always
        args:
        - "--redis.host=redis"
        ports:
        - containerPort: 8080
          name: http
        readinessProbe:
          httpGet:
            path: /
            port: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: nightbot-squads
  namespace: <%= $.namespace %>
  labels:
    name: nightbot-squads
spec:
  type: NodePort
  ports:
    - name: http
      port: 8080
      targetPort: http
  selector:
    name: nightbot-squads
